# -*- coding: utf-8 -*-
"""Rag_22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ung0u_IiOEeWBM-I2rSFQZX_Z_ES5IEN
"""

!pip install langchain langchain-community
!pip install faiss-cpu
!pip install sentence-transformers
!pip install transformers
!pip install pypdf

from google.colab import files
uploaded = files.upload()

from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("KEC_COLLEGE.pdf")

docs = loader.load()

print(len(docs))

!pip install langchain-text-splitters

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

chunks = splitter.split_documents(docs)

print(len(chunks))

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model="TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    max_new_tokens=50,
    do_sample=False
)

db = FAISS.from_documents(
    chunks,
    embeddings
)

retriever = db.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 2
    }
)

from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model="TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    max_new_tokens=40,
    do_sample=False
)

def ask(q):

    docs = retriever.invoke(q)

    context = " ".join([d.page_content for d in docs])

    prompt = f"""
Answer shortly.

Context:
{context}

Question: {q}
Answer:
"""

    result = pipe(
        prompt,
        max_new_tokens=40
    )[0]["generated_text"]

    return result.split("Answer:")[-1].strip()



ask("college name")

ask("cat prodecure in kongu?")

from fastapi import FastAPI
from transformers import pipeline

app = FastAPI()



@app.get("/ask")
def ask_api(question: str):

    answer = ask(question)

    return {"answer": answer}